# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('url', models.URLField()),
                ('order', models.IntegerField(blank=True, null=True, unique=True, verbose_name='순번')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('clicked', models.PositiveIntegerField(default=0, verbose_name='클릭수')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크 관리',
                'ordering': ['order'],
            },
        ),
    ]
