# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='audio_url',
            field=models.URLField(blank=True, help_text="'gs://cloud-storage-name/filename' 형식으로 적어주세요 ex) 'gs://speech-seul/file.flac'", null=True, verbose_name='음성파일 URL'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='lecture_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='제목'),
        ),
    ]
