# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0002_auto_20170908_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='메모'),
        ),
    ]
