# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0003_speech_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='lecture_date',
            field=models.DateField(blank=True, null=True, verbose_name='날짜'),
        ),
    ]
