# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_auto_20170908_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='audio_url',
            field=models.URLField(help_text="'gs://cloud-storage-name/filename' 형식으로 적어주세요 ex) 'gs://speech-seul/file.flac'", verbose_name='음성파일 URL'),
        ),
    ]
