# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0005_auto_20170909_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='audio_url',
            field=models.CharField(help_text="'gs://cloud-storage-name/filename' 형식으로 적어주세요 ex) 'gs://speech-seul/file.flac'", max_length=128, verbose_name='음성파일 URL'),
        ),
    ]
