# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0008_auto_20170912_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='file_name',
            field=models.CharField(default='test-1', help_text="파일 제목은 '.mp3', '.flac'을 제외한 파일명만 적어주세요! ex) '0906.mp3' 의 경우 '0906'", max_length=50, verbose_name='파일제목'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speech',
            name='audio_url',
            field=models.CharField(blank=True, help_text="'gs://cloud-storage-name/filename' 형식으로 적어주세요 ex) 'gs://speech-seul/file.flac'", max_length=128, null=True, verbose_name='음성파일 URL'),
        ),
    ]
