# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0009_auto_20170912_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='done',
            field=models.BooleanField(default=False, verbose_name='완료'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='file_name',
            field=models.CharField(help_text="파일 제목은 google-cloud-storage에 올린 파일의 '.mp3', '.flac'을 제외한 파일명만 적어주세요! ex) '0906.mp3' 의 경우 '0906'", max_length=50, verbose_name='파일제목'),
        ),
    ]
