# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0010_auto_20170912_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='operation_name',
            field=models.CharField(blank=True, help_text="google speech api를 호출할 때 사용하는 작업 번호입니다. 'GET https://speech.googleapis.com/v1/operations/YOUR_OPERATION_NAME?key=YOUR_API_KEY'의 YOUR_OPERATION_NAME에 넣어 주면 됩니다.", max_length=30, null=True, verbose_name='operation-name'),
        ),
    ]
