# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0014_auto_20170915_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'verbose_name': '대본', 'verbose_name_plural': '대본 관리'},
        ),
    ]
