# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0016_delete_weatherlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='api_data',
        ),
    ]
