# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0017_remove_speech_api_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='docx_input',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='수정전파일'),
        ),
        migrations.AddField(
            model_name='speech',
            name='docx_output',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='수정후파일'),
        ),
    ]
