# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0018_auto_20170919_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='content_done',
            field=models.TextField(blank=True, null=True, verbose_name='수정완료내용'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='수정전내용'),
        ),
    ]
