# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0019_auto_20170928_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='title',
        ),
        migrations.AlterField(
            model_name='speech',
            name='lecture_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='날짜'),
            preserve_default=False,
        ),
    ]
