# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('nid', models.IntegerField(unique=True, verbose_name='공지번호')),
                ('title', models.CharField(max_length=255, verbose_name='공지제목')),
                ('body', models.TextField(verbose_name='내용요약')),
                ('date', models.DateField(verbose_name='공지날짜')),
                ('detail_url', models.URLField(verbose_name='상세페이지')),
                ('is_new', models.BooleanField(default=True, verbose_name='새로운 공지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '경영대학원 공지',
                'verbose_name_plural': '경영대학원 공지 관리',
                'ordering': ['date'],
            },
        ),
    ]
