# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='detail_url',
            field=models.URLField(max_length=255, verbose_name='상세페이지'),
        ),
    ]
