# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20170920_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='detail_url',
            field=models.TextField(verbose_name='상세페이지'),
        ),
    ]
