# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20170920_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='중요'),
        ),
    ]
