# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_notice_is_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date'], 'verbose_name': '경영대학원 공지', 'verbose_name_plural': '경영대학원 공지 관리'},
        ),
    ]
