# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20170921_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
