# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('location', models.CharField(max_length=10, verbose_name='위치')),
                ('lat', models.CharField(max_length=10, verbose_name='위도')),
                ('lon', models.CharField(max_length=10, verbose_name='경도')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('order', models.IntegerField(blank=True, null=True, unique=True, verbose_name='순번')),
            ],
            options={
                'verbose_name': '날씨 위치',
                'verbose_name_plural': '날씨 위치 관리',
                'ordering': ['order'],
            },
        ),
    ]
